### PR TITLE
Generalize the operator pattern, plus some minor tweaks

### PR DESCRIPTION
**Pull request by nybble41**
1) Adjusted the pattern for hsOperator to include any sequence of operator characters other than two or more hyphens (so `-->` and `>--` are accepted, but `--` and `---` are not).

2) Adjusted the pattern for multi-character operators containing `.` to allow hyphens before and/or after the `.` (e.g. `.-` or `-.-`.)

3) The rule for type names only matched names preceded by a non-alphanumeric character. I added a case for matching type names at the beginning of a line.

4) The strings `qualified`, `as`, and `hiding` are only keywords within an import statement. In particular, `as` is often used to denote a list, e.g. `(a:as)`. I replaced the keyword declaration with a match statement similar to the one for the `family` keyword following `data` or `type`.

### CODE REVIEW

**Comment by geraldus** [comment]
Cool! I've just started to use vim and hasksyn few days ago. One thing I
can mention: _where_ keyword does not highlighted, however if type
semicolon after where if becomes highlighted (but this is not acceptable by
languages itself), looks like a bug.

2014-07-13 9:35 GMT+06:00 Jesse McDonald notifications@github.com:

**Comment by nybble41** [comment]
@geraldus Are you seeing the problem with the `where` keyword in all cases, or only some cases? I'm seeing highlighting for `where` both with and without a trailing semicolon, in both travitch/hasksyn and nybble41/hasksyn.

image

**Comment by geraldus** [comment]
Give me please about 15 minutes and I'll check new version behaviour (have to go now). In past it was related to `where`s nested within function declaration.

**Comment by geraldus** [comment]
I have MacVim, tested on `github` and `wombat256mod` colour schemes:
sample
Have not tested it with my gVim yet.

**Comment by nybble41** [comment]
@geraldus It looks like this is due to the `::` on the same line after the `where`. It was highlighted correctly until e76fbdf, which changed the pattern for `hsFunctionList` to fix a different problem. With the new pattern, the `where` is treated as a function name. I added commit ac62e20 to exclude the `where` (and `let`) keywords from the list of identifiers to the left of `::`. Please let me know if this fixes your issue.

**Comment by geraldus** [comment]
Hmm... I'm using Vundle, I've run `:PluginUpdate`, reopened MacVim and haskell file, but nothing changed. I figured out the behavior: when I type where it is highlighted, however when there is a double colons (`::`) after where keyword (on same line or on the following line) where becomes unhighlighted.
Sorry, but I haven't studied vimscript yet to be able to make changes by myself.

**Comment by nybble41** [comment]
@geraldus That sounds like the issue I fixed. Unless you selected my fork (nybble41/hasksyn) when you installed the plugin I wouldn't expect anything to change by running `:PluginUpdate`. My change isn't in the mainline version yet (travitch/hasksyn); thus this pull request.

**Comment by geraldus** [comment]
Since I'm also git newbie I do not know how to work properly with branches and pull requests (I'm using git majorly to commit and push changes), so I just copied your updates to my local file and I can confirm now that `where` is being highlighted properly. Thank you!

**Pull request merged**
